//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryWeb.AuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name sServicePassword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUISPassword", ReplyAction="*")]
        GalleryWeb.AuthService.CUISPasswordResponse CUISPassword(GalleryWeb.AuthService.CUISPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUISPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<GalleryWeb.AuthService.CUISPasswordResponse> CUISPasswordAsync(GalleryWeb.AuthService.CUISPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CUISPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CUISPassword", Namespace="http://tempuri.org/", Order=0)]
        public GalleryWeb.AuthService.CUISPasswordRequestBody Body;
        
        public CUISPasswordRequest() {
        }
        
        public CUISPasswordRequest(GalleryWeb.AuthService.CUISPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CUISPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sServicePassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPassword;
        
        public CUISPasswordRequestBody() {
        }
        
        public CUISPasswordRequestBody(string sServicePassword, string sUserID, string sPassword) {
            this.sServicePassword = sServicePassword;
            this.sUserID = sUserID;
            this.sPassword = sPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CUISPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CUISPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public GalleryWeb.AuthService.CUISPasswordResponseBody Body;
        
        public CUISPasswordResponse() {
        }
        
        public CUISPasswordResponse(GalleryWeb.AuthService.CUISPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CUISPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CUISPasswordResult;
        
        public CUISPasswordResponseBody() {
        }
        
        public CUISPasswordResponseBody(bool CUISPasswordResult) {
            this.CUISPasswordResult = CUISPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : GalleryWeb.AuthService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<GalleryWeb.AuthService.ServiceSoap>, GalleryWeb.AuthService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GalleryWeb.AuthService.CUISPasswordResponse GalleryWeb.AuthService.ServiceSoap.CUISPassword(GalleryWeb.AuthService.CUISPasswordRequest request) {
            return base.Channel.CUISPassword(request);
        }
        
        public bool CUISPassword(string sServicePassword, string sUserID, string sPassword) {
            GalleryWeb.AuthService.CUISPasswordRequest inValue = new GalleryWeb.AuthService.CUISPasswordRequest();
            inValue.Body = new GalleryWeb.AuthService.CUISPasswordRequestBody();
            inValue.Body.sServicePassword = sServicePassword;
            inValue.Body.sUserID = sUserID;
            inValue.Body.sPassword = sPassword;
            GalleryWeb.AuthService.CUISPasswordResponse retVal = ((GalleryWeb.AuthService.ServiceSoap)(this)).CUISPassword(inValue);
            return retVal.Body.CUISPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GalleryWeb.AuthService.CUISPasswordResponse> GalleryWeb.AuthService.ServiceSoap.CUISPasswordAsync(GalleryWeb.AuthService.CUISPasswordRequest request) {
            return base.Channel.CUISPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<GalleryWeb.AuthService.CUISPasswordResponse> CUISPasswordAsync(string sServicePassword, string sUserID, string sPassword) {
            GalleryWeb.AuthService.CUISPasswordRequest inValue = new GalleryWeb.AuthService.CUISPasswordRequest();
            inValue.Body = new GalleryWeb.AuthService.CUISPasswordRequestBody();
            inValue.Body.sServicePassword = sServicePassword;
            inValue.Body.sUserID = sUserID;
            inValue.Body.sPassword = sPassword;
            return ((GalleryWeb.AuthService.ServiceSoap)(this)).CUISPasswordAsync(inValue);
        }
    }
}
